-- ============================================================================
-- AeroSight Snowflake Dimension Tables
-- 02_create_dimensions.sql
-- ============================================================================

USE DATABASE AEROSIGHT_DB;
USE SCHEMA GOLD;

-- 1. DIM_DATE
CREATE OR REPLACE TABLE DIM_DATE (
    DATE_KEY INT PRIMARY KEY,
    FLIGHT_DATE DATE NOT NULL,
    YEAR INT NOT NULL,
    QUARTER INT NOT NULL,
    MONTH INT NOT NULL,
    MONTH_NAME VARCHAR(20) NOT NULL,
    DAY_OF_MONTH INT NOT NULL,
    DAY_OF_WEEK INT NOT NULL,
    DAY_NAME VARCHAR(20) NOT NULL,
    IS_WEEKEND INT NOT NULL
);

-- 2. DIM_AIRPORT
CREATE OR REPLACE TABLE DIM_AIRPORT (
    AIRPORT_KEY VARCHAR(10) PRIMARY KEY,
    IATA VARCHAR(3) NOT NULL,
    ICAO VARCHAR(4),
    NAME VARCHAR(150) NOT NULL,
    CITY VARCHAR(100) NOT NULL,
    STATE VARCHAR(10) NOT NULL,
    LAT FLOAT NOT NULL,
    LON FLOAT NOT NULL,
    ELEV INT,
    TZ VARCHAR(50),
    HUB VARCHAR(30),
    TERMINALS INT,
    GATES INT
);

-- 3. DIM_AIRLINE
CREATE OR REPLACE TABLE DIM_AIRLINE (
    AIRLINE_KEY VARCHAR(10) PRIMARY KEY,
    CARRIER_CODE VARCHAR(3) NOT NULL,
    AIRLINE_NAME VARCHAR(100) NOT NULL,
    CALLSIGN VARCHAR(50),
    COUNTRY VARCHAR(50),
    FLEET_SIZE INT,
    PRIMARY_HUB VARCHAR(10)
);

-- 4. DIM_ROUTE
CREATE OR REPLACE TABLE DIM_ROUTE (
    ROUTE_KEY VARCHAR(20) PRIMARY KEY,
    ORIGIN_AIRPORT VARCHAR(10) NOT NULL,
    DEST_AIRPORT VARCHAR(10) NOT NULL,
    DISTANCE_MILES INT NOT NULL,
    AVG_SCHEDULED_ELAPSED_MIN FLOAT,
    HISTORICAL_FLIGHT_COUNT INT,
    DISTANCE_CATEGORY VARCHAR(50)
);

-- 5. DIM_AIRCRAFT
CREATE OR REPLACE TABLE DIM_AIRCRAFT (
    AIRCRAFT_KEY VARCHAR(20) PRIMARY KEY,
    TAIL_NUMBER VARCHAR(20) NOT NULL,
    CARRIER_CODE VARCHAR(10),
    MODEL VARCHAR(100),
    MANUFACTURER VARCHAR(100),
    SEAT_CAPACITY INT,
    CRUISE_SPEED_KNOTS INT,
    YEAR_MANUFACTURED INT
);
