-- ============================================================================
-- AeroSight Snowflake Fact Tables
-- 03_create_facts.sql
-- ============================================================================

USE DATABASE AEROSIGHT_DB;
USE SCHEMA GOLD;

-- 1. FACT_FLIGHTS
CREATE OR REPLACE TABLE FACT_FLIGHTS (
    FLIGHT_ID VARCHAR(50) PRIMARY KEY,
    DATE_KEY INT REFERENCES DIM_DATE(DATE_KEY),
    FLIGHT_DATE DATE NOT NULL,
    CARRIER_KEY VARCHAR(10) REFERENCES DIM_AIRLINE(AIRLINE_KEY),
    FLIGHT_NUMBER INT NOT NULL,
    AIRCRAFT_KEY VARCHAR(20) REFERENCES DIM_AIRCRAFT(AIRCRAFT_KEY),
    ORIGIN_AIRPORT_KEY VARCHAR(10) REFERENCES DIM_AIRPORT(AIRPORT_KEY),
    DEST_AIRPORT_KEY VARCHAR(10) REFERENCES DIM_AIRPORT(AIRPORT_KEY),
    ROUTE_KEY VARCHAR(20) REFERENCES DIM_ROUTE(ROUTE_KEY),
    CRS_DEP_TIME INT NOT NULL,
    DEP_TIME INT,
    DEP_DELAY FLOAT,
    TAXI_OUT FLOAT,
    WHEELS_OFF INT,
    WHEELS_ON INT,
    TAXI_IN FLOAT,
    CRS_ARR_TIME INT NOT NULL,
    ARR_TIME INT,
    ARR_DELAY FLOAT,
    CANCELLED INT NOT NULL DEFAULT 0,
    CANCELLATION_CODE VARCHAR(5),
    DIVERTED INT NOT NULL DEFAULT 0,
    CRS_ELAPSED_TIME INT,
    ACTUAL_ELAPSED_TIME FLOAT,
    AIR_TIME FLOAT,
    DISTANCE INT NOT NULL,
    IS_DELAYED_15 INT NOT NULL DEFAULT 0,
    IS_DELAYED_45 INT NOT NULL DEFAULT 0,
    IS_SEVERE_DELAY INT NOT NULL DEFAULT 0,
    ORIGIN_TEMP_F FLOAT,
    ORIGIN_WIND_MPH FLOAT,
    ORIGIN_VISIBILITY_MILES FLOAT,
    ORIGIN_WEATHER_CONDITION VARCHAR(50),
    DEST_TEMP_F FLOAT,
    DEST_WIND_MPH FLOAT,
    DEST_VISIBILITY_MILES FLOAT,
    DEST_WEATHER_CONDITION VARCHAR(50)
)
CLUSTER BY (FLIGHT_DATE, CARRIER_KEY, ORIGIN_AIRPORT_KEY);

-- 2. FACT_DELAYS
CREATE OR REPLACE TABLE FACT_DELAYS (
    FLIGHT_ID VARCHAR(50) PRIMARY KEY,
    DATE_KEY INT REFERENCES DIM_DATE(DATE_KEY),
    CARRIER_KEY VARCHAR(10) REFERENCES DIM_AIRLINE(AIRLINE_KEY),
    ORIGIN_AIRPORT_KEY VARCHAR(10) REFERENCES DIM_AIRPORT(AIRPORT_KEY),
    DEST_AIRPORT_KEY VARCHAR(10) REFERENCES DIM_AIRPORT(AIRPORT_KEY),
    DEP_DELAY FLOAT NOT NULL,
    ARR_DELAY FLOAT NOT NULL,
    CARRIER_DELAY FLOAT DEFAULT 0.0,
    WEATHER_DELAY FLOAT DEFAULT 0.0,
    NAS_DELAY FLOAT DEFAULT 0.0,
    SECURITY_DELAY FLOAT DEFAULT 0.0,
    LATE_AIRCRAFT_DELAY FLOAT DEFAULT 0.0,
    PRIMARY_DELAY_CAUSE VARCHAR(50) NOT NULL
)
CLUSTER BY (CARRIER_KEY, PRIMARY_DELAY_CAUSE);

-- 3. FACT_BAGGAGE
CREATE OR REPLACE TABLE FACT_BAGGAGE (
    EVENT_ID VARCHAR(50) PRIMARY KEY,
    FLIGHT_ID VARCHAR(50) NOT NULL,
    CARRIER_CODE VARCHAR(10) NOT NULL,
    ORIGIN_AIRPORT VARCHAR(10) NOT NULL,
    DEST_AIRPORT VARCHAR(10) NOT NULL,
    TOTAL_CHECKED_BAGS INT NOT NULL,
    LOADED_BAGS INT NOT NULL,
    DELAYED_BAGS INT NOT NULL,
    MISHANDLED_BAG_RATE_PCT FLOAT NOT NULL,
    AVG_CAROUSEL_WAIT_MIN FLOAT NOT NULL,
    TIMESTAMP TIMESTAMP_NTZ NOT NULL
);
