-- ============================================================================
-- AeroSight Snowflake Gold Ingestion (COPY INTO)
-- 04_load_gold_to_snowflake.sql
-- ============================================================================

USE DATABASE AEROSIGHT_DB;
USE SCHEMA GOLD;

-- 1. Create External Stage pointing to Cloud Storage (e.g. S3 / GCS / Azure)
CREATE OR REPLACE STAGE AEROSIGHT_GOLD_STAGE
    URL = 's3://aerosight-data-platform/gold/'
    FILE_FORMAT = (TYPE = 'PARQUET');

-- 2. Load Dimensions from Stage
COPY INTO DIM_DATE FROM @AEROSIGHT_GOLD_STAGE/dim_date/ MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;
COPY INTO DIM_AIRPORT FROM @AEROSIGHT_GOLD_STAGE/dim_airport/ MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;
COPY INTO DIM_AIRLINE FROM @AEROSIGHT_GOLD_STAGE/dim_airline/ MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;
COPY INTO DIM_ROUTE FROM @AEROSIGHT_GOLD_STAGE/dim_route/ MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;
COPY INTO DIM_AIRCRAFT FROM @AEROSIGHT_GOLD_STAGE/dim_aircraft/ MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

-- 3. Load Facts from Stage
COPY INTO FACT_FLIGHTS FROM @AEROSIGHT_GOLD_STAGE/fact_flights/ MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;
COPY INTO FACT_DELAYS FROM @AEROSIGHT_GOLD_STAGE/fact_delays/ MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

-- 4. Verify Record Counts
SELECT 'DIM_DATE' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM DIM_DATE
UNION ALL
SELECT 'DIM_AIRPORT', COUNT(*) FROM DIM_AIRPORT
UNION ALL
SELECT 'DIM_AIRLINE', COUNT(*) FROM DIM_AIRLINE
UNION ALL
SELECT 'DIM_ROUTE', COUNT(*) FROM DIM_ROUTE
UNION ALL
SELECT 'DIM_AIRCRAFT', COUNT(*) FROM DIM_AIRCRAFT
UNION ALL
SELECT 'FACT_FLIGHTS', COUNT(*) FROM FACT_FLIGHTS
UNION ALL
SELECT 'FACT_DELAYS', COUNT(*) FROM FACT_DELAYS;
